#Goal
float64 revolut1
float64 revolut2
float64 revolut3
float64 revolut4
float64 revolut5
float64 revolut6
float64 revolut7
float64 revolut8
float64 revolut9
float64 revolut10
float64 revolut11
float64 revolut12
float64 revolut13
float64 revolut14
float64 revolut15
float64 revolut16
float64 revolut17
float64 revolut18

---
#Result
bool success
---
#Feedback
float32 time_left
